'use server';

import { revalidatePath } from 'next/cache';
import { createClient } from '@/lib/supabase/server';
import { encryptApiKey, decryptApiKey } from '@/lib/utils/encryption';
import { isAdmin } from '@/lib/utils/roles';
import { logger } from '@/lib/utils/logger';
import { logAudit } from '@/lib/utils/audit';

// ---------------------------------------------------------------------------
// createClient - insert a new client
// ---------------------------------------------------------------------------

interface ClientData {
  raison_sociale: string;
  siret?: string | null;
  adresse?: string | null;
  localisation?: string | null;
  tva_intracommunautaire?: string | null;
  numero_qualiopi?: string | null;
  numero_nda?: string | null;
  numero_uai?: string | null;
}

export async function createClientAction(
  data: ClientData,
): Promise<{ success: boolean; id?: string; error?: string }> {
  if (!data.raison_sociale?.trim()) {
    return { success: false, error: 'La raison sociale est requise' };
  }

  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { success: false, error: 'Non authentifié' };

  const { data: caller } = await supabase
    .from('users')
    .select('role')
    .eq('id', user.id)
    .single();
  if (!isAdmin(caller?.role)) {
    return { success: false, error: 'Accès réservé aux administrateurs' };
  }

  // trigramme is auto-generated by DB trigger when empty
  const { data: client, error } = await supabase
    .from('clients')
    .insert({
      raison_sociale: data.raison_sociale.trim(),
      trigramme: '',
      siret: data.siret?.trim() || null,
      adresse: data.adresse?.trim() || null,
      localisation: data.localisation?.trim() || null,
      tva_intracommunautaire: data.tva_intracommunautaire?.trim() || null,
      numero_qualiopi: data.numero_qualiopi?.trim() || null,
      numero_nda: data.numero_nda?.trim() || null,
      numero_uai: data.numero_uai?.trim() || null,
    })
    .select('id')
    .single();

  if (error) return { success: false, error: error.message };

  logAudit('client_created', 'client', client.id);

  revalidatePath('/admin/clients');

  return { success: true, id: client.id };
}

// ---------------------------------------------------------------------------
// updateClient - update an existing client
// ---------------------------------------------------------------------------

export async function updateClientAction(
  id: string,
  data: ClientData,
): Promise<{ success: boolean; error?: string }> {
  if (!data.raison_sociale?.trim()) {
    return { success: false, error: 'La raison sociale est requise' };
  }

  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { success: false, error: 'Non authentifié' };

  const { data: caller } = await supabase
    .from('users')
    .select('role')
    .eq('id', user.id)
    .single();
  if (!isAdmin(caller?.role)) {
    return { success: false, error: 'Accès réservé aux administrateurs' };
  }

  const { error } = await supabase
    .from('clients')
    .update({
      raison_sociale: data.raison_sociale.trim(),
      siret: data.siret?.trim() || null,
      adresse: data.adresse?.trim() || null,
      localisation: data.localisation?.trim() || null,
      tva_intracommunautaire: data.tva_intracommunautaire?.trim() || null,
      numero_qualiopi: data.numero_qualiopi?.trim() || null,
      numero_nda: data.numero_nda?.trim() || null,
      numero_uai: data.numero_uai?.trim() || null,
    })
    .eq('id', id);

  if (error) return { success: false, error: error.message };

  logAudit('client_updated', 'client', id);

  revalidatePath('/admin/clients');
  revalidatePath(`/admin/clients/${id}`);

  return { success: true };
}

// ---------------------------------------------------------------------------
// archiveClient - soft delete (archive = true)
// ---------------------------------------------------------------------------

export async function archiveClient(
  id: string,
): Promise<{ success: boolean; error?: string }> {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { success: false, error: 'Non authentifié' };

  const { data: caller } = await supabase
    .from('users')
    .select('role')
    .eq('id', user.id)
    .single();
  if (!isAdmin(caller?.role)) {
    return { success: false, error: 'Accès réservé aux administrateurs' };
  }

  const { error } = await supabase
    .from('clients')
    .update({ archive: true })
    .eq('id', id);

  if (error) return { success: false, error: error.message };

  logAudit('client_archived', 'client', id);

  revalidatePath('/admin/clients');

  return { success: true };
}

// ---------------------------------------------------------------------------
// unarchiveClient - restore (archive = false)
// ---------------------------------------------------------------------------

export async function unarchiveClient(
  id: string,
): Promise<{ success: boolean; error?: string }> {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { success: false, error: 'Non authentifié' };

  const { data: caller } = await supabase
    .from('users')
    .select('role')
    .eq('id', user.id)
    .single();
  if (!isAdmin(caller?.role)) {
    return { success: false, error: 'Accès réservé aux administrateurs' };
  }

  const { error } = await supabase
    .from('clients')
    .update({ archive: false })
    .eq('id', id);

  if (error) return { success: false, error: error.message };

  logAudit('client_unarchived', 'client', id);

  revalidatePath('/admin/clients');
  revalidatePath(`/admin/clients/${id}`);

  return { success: true };
}

// ---------------------------------------------------------------------------
// addClientContact - insert into client_contacts
// ---------------------------------------------------------------------------

interface ContactData {
  nom: string;
  poste?: string | null;
  email?: string | null;
  telephone?: string | null;
}

export async function addClientContact(
  clientId: string,
  data: ContactData,
): Promise<{ success: boolean; error?: string }> {
  if (!data.nom?.trim()) {
    return { success: false, error: 'Le nom est requis' };
  }

  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { success: false, error: 'Non authentifié' };

  const { error } = await supabase.from('client_contacts').insert({
    client_id: clientId,
    nom: data.nom.trim(),
    poste: data.poste?.trim() || null,
    email: data.email?.trim() || null,
    telephone: data.telephone?.trim() || null,
  });

  if (error) return { success: false, error: error.message };

  logAudit('contact_added', 'client', clientId, { nom: data.nom });

  revalidatePath(`/admin/clients/${clientId}`);

  return { success: true };
}

// ---------------------------------------------------------------------------
// deleteClientContact - hard delete from client_contacts
// ---------------------------------------------------------------------------

export async function deleteClientContact(
  contactId: string,
  clientId: string,
): Promise<{ success: boolean; error?: string }> {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { success: false, error: 'Non authentifié' };

  const { error } = await supabase
    .from('client_contacts')
    .delete()
    .eq('id', contactId);

  if (error) return { success: false, error: error.message };

  logAudit('contact_deleted', 'client', contactId);

  revalidatePath(`/admin/clients/${clientId}`);

  return { success: true };
}

// ---------------------------------------------------------------------------
// addClientNote - insert into client_notes
// ---------------------------------------------------------------------------

export async function addClientNote(
  clientId: string,
  contenu: string,
): Promise<{ success: boolean; error?: string }> {
  if (!contenu?.trim()) {
    return { success: false, error: 'Le contenu est requis' };
  }

  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { success: false, error: 'Non authentifié' };

  const { error } = await supabase.from('client_notes').insert({
    client_id: clientId,
    user_id: user.id,
    contenu: contenu.trim(),
  });

  if (error) return { success: false, error: error.message };

  logAudit('note_added', 'client', clientId);

  revalidatePath(`/admin/clients/${clientId}`);

  return { success: true };
}

// ---------------------------------------------------------------------------
// addClientApiKey - insert into client_api_keys with encrypted key
// ---------------------------------------------------------------------------

export async function addClientApiKey(
  clientId: string,
  data: {
    instanceUrl: string;
    apiKey: string;
    label: string;
  },
): Promise<{ success: boolean; error?: string }> {
  if (!data.instanceUrl?.trim()) {
    return { success: false, error: "L'URL de l'instance est requise" };
  }

  if (!data.instanceUrl.includes('.eduvia.app')) {
    return {
      success: false,
      error: "L'URL doit contenir .eduvia.app (ex: dupont.eduvia.app)",
    };
  }

  if (!data.apiKey?.trim()) {
    return { success: false, error: 'La clé API est requise' };
  }

  if (!data.label?.trim()) {
    return { success: false, error: 'Le libellé est requis' };
  }

  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { success: false, error: 'Non authentifié' };

  const { data: caller } = await supabase
    .from('users')
    .select('role')
    .eq('id', user.id)
    .single();
  if (!isAdmin(caller?.role)) {
    return { success: false, error: 'Accès réservé aux administrateurs' };
  }

  let apiKeyEncrypted: string;
  try {
    apiKeyEncrypted = encryptApiKey(data.apiKey.trim());
  } catch (err) {
    logger.warn(
      'actions.clients',
      'ENCRYPTION_KEY non disponible, stockage en clair',
      { error: err instanceof Error ? err.message : String(err) },
    );
    // Fallback: store as-is when ENCRYPTION_KEY is not configured
    apiKeyEncrypted = data.apiKey.trim();
  }

  const { error } = await supabase.from('client_api_keys').insert({
    client_id: clientId,
    instance_url: data.instanceUrl.trim(),
    api_key_encrypted: apiKeyEncrypted,
    label: data.label.trim(),
    is_active: true,
  });

  if (error) return { success: false, error: error.message };

  logAudit('apikey_added', 'client', clientId, { label: data.label });

  revalidatePath(`/admin/clients/${clientId}`);

  return { success: true };
}

// ---------------------------------------------------------------------------
// deleteClientApiKey - hard delete from client_api_keys
// ---------------------------------------------------------------------------

export async function deleteClientApiKey(
  keyId: string,
): Promise<{ success: boolean; error?: string }> {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { success: false, error: 'Non authentifié' };

  const { data: caller } = await supabase
    .from('users')
    .select('role')
    .eq('id', user.id)
    .single();
  if (!isAdmin(caller?.role)) {
    return { success: false, error: 'Accès réservé aux administrateurs' };
  }

  // Get client_id before deleting for revalidation
  const { data: keyRow } = await supabase
    .from('client_api_keys')
    .select('client_id')
    .eq('id', keyId)
    .single();

  const { error } = await supabase
    .from('client_api_keys')
    .delete()
    .eq('id', keyId);

  if (error) return { success: false, error: error.message };

  logAudit('apikey_deleted', 'client', keyId);

  if (keyRow) {
    revalidatePath(`/admin/clients/${keyRow.client_id}`);
  }

  return { success: true };
}

// ---------------------------------------------------------------------------
// toggleClientApiKeyActive - toggle is_active on client_api_keys
// ---------------------------------------------------------------------------

export async function toggleClientApiKeyActive(
  keyId: string,
  isActive: boolean,
): Promise<{ success: boolean; error?: string }> {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { success: false, error: 'Non authentifié' };

  const { data: caller } = await supabase
    .from('users')
    .select('role')
    .eq('id', user.id)
    .single();
  if (!isAdmin(caller?.role)) {
    return { success: false, error: 'Accès réservé aux administrateurs' };
  }

  const { error } = await supabase
    .from('client_api_keys')
    .update({ is_active: isActive })
    .eq('id', keyId);

  if (error) return { success: false, error: error.message };

  logAudit('apikey_toggled', 'client', keyId, { isActive });

  // Get client_id for revalidation
  const { data: keyRow } = await supabase
    .from('client_api_keys')
    .select('client_id')
    .eq('id', keyId)
    .single();

  if (keyRow) {
    revalidatePath(`/admin/clients/${keyRow.client_id}`);
  }

  return { success: true };
}

// ---------------------------------------------------------------------------
// testApiKeyConnection - test connectivity to Eduvia instance
// ---------------------------------------------------------------------------

export async function testApiKeyConnection(
  keyId: string,
): Promise<{ success: boolean; error?: string }> {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { success: false, error: 'Non authentifié' };

  const { data: caller } = await supabase
    .from('users')
    .select('role')
    .eq('id', user.id)
    .single();
  if (!isAdmin(caller?.role)) {
    return { success: false, error: 'Accès réservé aux administrateurs' };
  }

  const { data: keyRow, error: fetchError } = await supabase
    .from('client_api_keys')
    .select('api_key_encrypted, instance_url')
    .eq('id', keyId)
    .single();

  if (fetchError || !keyRow) {
    return { success: false, error: 'Clé API introuvable' };
  }

  if (!keyRow.instance_url) {
    return { success: false, error: "URL d'instance manquante" };
  }

  let apiKey: string;
  try {
    apiKey = decryptApiKey(keyRow.api_key_encrypted);
  } catch {
    // If decryption fails, try using the raw value (unencrypted fallback)
    apiKey = keyRow.api_key_encrypted;
  }

  const baseUrl = keyRow.instance_url.replace(/\/$/, '');
  const url = baseUrl.startsWith('http')
    ? `${baseUrl}/api/v1/status`
    : `https://${baseUrl}/api/v1/status`;

  try {
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        Accept: 'application/json',
      },
      signal: AbortSignal.timeout(5_000),
    });

    if (!response.ok) {
      return {
        success: false,
        error: `Erreur HTTP ${response.status} : ${response.statusText}`,
      };
    }

    return { success: true };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return {
      success: false,
      error: `Connexion échouée : ${message}`,
    };
  }
}
