'use server';

import { revalidatePath } from 'next/cache';
import { createClient } from '@/lib/supabase/server';

// ---------------------------------------------------------------------------
// createClient — insert a new client
// ---------------------------------------------------------------------------

interface ClientData {
  raison_sociale: string;
  siret?: string | null;
  adresse?: string | null;
  localisation?: string | null;
  tva_intracommunautaire?: string | null;
  numero_qualiopi?: string | null;
  numero_nda?: string | null;
  numero_uai?: string | null;
}

export async function createClientAction(
  data: ClientData,
): Promise<{ success: boolean; id?: string; error?: string }> {
  if (!data.raison_sociale?.trim()) {
    return { success: false, error: 'La raison sociale est requise' };
  }

  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { success: false, error: 'Non authentifie' };

  const { data: caller } = await supabase
    .from('users')
    .select('role')
    .eq('id', user.id)
    .single();
  if (caller?.role !== 'admin') {
    return { success: false, error: 'Acces reserve aux administrateurs' };
  }

  // trigramme is auto-generated by DB trigger when empty
  const { data: client, error } = await supabase
    .from('clients')
    .insert({
      raison_sociale: data.raison_sociale.trim(),
      trigramme: '',
      siret: data.siret?.trim() || null,
      adresse: data.adresse?.trim() || null,
      localisation: data.localisation?.trim() || null,
      tva_intracommunautaire: data.tva_intracommunautaire?.trim() || null,
      numero_qualiopi: data.numero_qualiopi?.trim() || null,
      numero_nda: data.numero_nda?.trim() || null,
      numero_uai: data.numero_uai?.trim() || null,
    })
    .select('id')
    .single();

  if (error) return { success: false, error: error.message };

  revalidatePath('/admin/clients');

  return { success: true, id: client.id };
}

// ---------------------------------------------------------------------------
// updateClient — update an existing client
// ---------------------------------------------------------------------------

export async function updateClientAction(
  id: string,
  data: ClientData,
): Promise<{ success: boolean; error?: string }> {
  if (!data.raison_sociale?.trim()) {
    return { success: false, error: 'La raison sociale est requise' };
  }

  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { success: false, error: 'Non authentifie' };

  const { data: caller } = await supabase
    .from('users')
    .select('role')
    .eq('id', user.id)
    .single();
  if (caller?.role !== 'admin') {
    return { success: false, error: 'Acces reserve aux administrateurs' };
  }

  const { error } = await supabase
    .from('clients')
    .update({
      raison_sociale: data.raison_sociale.trim(),
      siret: data.siret?.trim() || null,
      adresse: data.adresse?.trim() || null,
      localisation: data.localisation?.trim() || null,
      tva_intracommunautaire: data.tva_intracommunautaire?.trim() || null,
      numero_qualiopi: data.numero_qualiopi?.trim() || null,
      numero_nda: data.numero_nda?.trim() || null,
      numero_uai: data.numero_uai?.trim() || null,
    })
    .eq('id', id);

  if (error) return { success: false, error: error.message };

  revalidatePath('/admin/clients');
  revalidatePath(`/admin/clients/${id}`);

  return { success: true };
}

// ---------------------------------------------------------------------------
// archiveClient — soft delete (archive = true)
// ---------------------------------------------------------------------------

export async function archiveClient(
  id: string,
): Promise<{ success: boolean; error?: string }> {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { success: false, error: 'Non authentifie' };

  const { data: caller } = await supabase
    .from('users')
    .select('role')
    .eq('id', user.id)
    .single();
  if (caller?.role !== 'admin') {
    return { success: false, error: 'Acces reserve aux administrateurs' };
  }

  const { error } = await supabase
    .from('clients')
    .update({ archive: true })
    .eq('id', id);

  if (error) return { success: false, error: error.message };

  revalidatePath('/admin/clients');

  return { success: true };
}

// ---------------------------------------------------------------------------
// addClientContact — insert into client_contacts
// ---------------------------------------------------------------------------

interface ContactData {
  nom: string;
  poste?: string | null;
  email?: string | null;
  telephone?: string | null;
}

export async function addClientContact(
  clientId: string,
  data: ContactData,
): Promise<{ success: boolean; error?: string }> {
  if (!data.nom?.trim()) {
    return { success: false, error: 'Le nom est requis' };
  }

  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { success: false, error: 'Non authentifie' };

  const { error } = await supabase.from('client_contacts').insert({
    client_id: clientId,
    nom: data.nom.trim(),
    poste: data.poste?.trim() || null,
    email: data.email?.trim() || null,
    telephone: data.telephone?.trim() || null,
  });

  if (error) return { success: false, error: error.message };

  revalidatePath(`/admin/clients/${clientId}`);

  return { success: true };
}

// ---------------------------------------------------------------------------
// deleteClientContact — hard delete from client_contacts
// ---------------------------------------------------------------------------

export async function deleteClientContact(
  contactId: string,
  clientId: string,
): Promise<{ success: boolean; error?: string }> {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { success: false, error: 'Non authentifie' };

  const { error } = await supabase
    .from('client_contacts')
    .delete()
    .eq('id', contactId);

  if (error) return { success: false, error: error.message };

  revalidatePath(`/admin/clients/${clientId}`);

  return { success: true };
}

// ---------------------------------------------------------------------------
// addClientNote — insert into client_notes
// ---------------------------------------------------------------------------

export async function addClientNote(
  clientId: string,
  contenu: string,
): Promise<{ success: boolean; error?: string }> {
  if (!contenu?.trim()) {
    return { success: false, error: 'Le contenu est requis' };
  }

  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { success: false, error: 'Non authentifie' };

  const { error } = await supabase.from('client_notes').insert({
    client_id: clientId,
    user_id: user.id,
    contenu: contenu.trim(),
  });

  if (error) return { success: false, error: error.message };

  revalidatePath(`/admin/clients/${clientId}`);

  return { success: true };
}
